### ISSUE TITLE
Multiple Streams using AioQuic

### ISSUE THREAD

**Issue by devkdas** [yutakahirano/aioquic-transport#1]
hai ,

It is not an issue.
one small quick query

@yutakahirano 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code you have in Github.

Sorry for raising an issue as i am unable to find your email to ask this query.

Looking forward for your reply

Thank you.

**Comment by yutakahirano** [comment]
I think the answer is yes.

**Comment by devkdas** [comment]
Hai,

Thank you for replying back @yutakahirano 

Myself Karthik.I am trying to use the "AioQuic" to write some python scripts.
I am trying to download a file(s) using the script and able to download the file(s).

But one small problem is only one single stream is being created between client and server to download the whole file.
Now I am trying to find out a way to download file(s) by creating multiple streams.

Could you please help me how to create multiple streams to download a file(s) in a single connection. @yutakahirano 

I am currently using "Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-113-generic x86_64)","Python 3.8.10" version for running both http3_client.py and http3_server.py.

Hope you are also using Linux where you have created multiple streams in a single connection using AIOQUIC. @yutakahirano 

Could you please confirm did you made any changes to the AIOQUIC code to create multiple streams in a single connection @yutakahirano 

I am not able to get what am i missing.

Attached quic log image for your reference

Hope you will reply soon.

Thanks and Regards,
Karthik.
<img width="895" alt="aioquic_file" src="https://user-images.githubusercontent.com/92445174/173753069-c230bc0d-3789-4d5d-94b5-a38f30525b0c.PNG">

**Comment by yutakahirano** [comment]
Sorry I'm not a developer of aioquic, just a user.

**Comment by devkdas** [comment]
Okay,

Could you please answer these 2 queries @yutakahirano 

1.Could you please confirm did you made any changes to the AIOQUIC code to create multiple streams in a single connection @yutakahirano

2.Could you please confirm were you also using Linux(Ubuntu,Centos,etc) terminal or Linux GUI(Chrome,Firefox etc) or totally different OS(like Windows,MAC) where you have created multiple streams in a single connection using AIOQUIC. @yutakahirano


Looking forward for your answer to  these 2 queries.

Thank you.

**Comment by yutakahirano** [comment]
I'm using Windows but I also run the code on Linux. IIRC I had no problem to create multiple streams on a connection.

**Comment by devkdas** [comment]
Okay

Could you please confirm did you made any changes to the AIOQUIC code or not to create multiple streams in a single connection

If possible and comfortable , Could you please share me the code and commands that you have used in Linux terminal where you were able to create multiple streams on a single connection.

**Comment by yutakahirano** [comment]
I made some modification but that was not to create multiple streams on a single connection.

I have a working example - https://github.com/web-platform-tests/wpt/tree/master/tools/webtransport but I don't have time to explain how to run it in detail.

**Comment by devkdas** [comment]
No problem,I will try to undertstand and will try to run.

Thank you for Sharing and Helping.
